openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: '{protocol}://localhost:4500'
    description: this is just a dummy
    variables:
      protocol:
        enum:
          - https
          - http
        default: http

paths:
  /:
    get:
      tags:
        - Strings